// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw0nXL11R15UeDywR8OHiq9YvoKGxowu4',
    appId: '1:785432683595:web:f4567dff0016d5768a99ce',
    messagingSenderId: '785432683595',
    projectId: 'daily-grind-3426d',
    authDomain: 'daily-grind-3426d.firebaseapp.com',
    storageBucket: 'daily-grind-3426d.appspot.com',
    measurementId: 'G-QB0KP8KTSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XbwXVj4K4l3-_op26fCfqjyndk-58Ik',
    appId: '1:785432683595:android:29104aced94306088a99ce',
    messagingSenderId: '785432683595',
    projectId: 'daily-grind-3426d',
    storageBucket: 'daily-grind-3426d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPAOSDeHm9A7w6RotxwVPmjrPwaY79Wc',
    appId: '1:785432683595:ios:cd372b05d22b24b48a99ce',
    messagingSenderId: '785432683595',
    projectId: 'daily-grind-3426d',
    storageBucket: 'daily-grind-3426d.appspot.com',
    iosClientId:
        '785432683595-tiuu34t8h1lq1b2476d6htd8iap78fn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyGrind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCPAOSDeHm9A7w6RotxwVPmjrPwaY79Wc',
    appId: '1:785432683595:ios:cd372b05d22b24b48a99ce',
    messagingSenderId: '785432683595',
    projectId: 'daily-grind-3426d',
    storageBucket: 'daily-grind-3426d.appspot.com',
    iosClientId:
        '785432683595-tiuu34t8h1lq1b2476d6htd8iap78fn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyGrind',
  );
}
